// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrJ2NBr9ib1AdD0DKSXXogrPyBPGs1Rb0',
    appId: '1:966413108999:web:c19cabb4bd93f2fea8e7a2',
    messagingSenderId: '966413108999',
    projectId: 'flutter-final-43726',
    authDomain: 'flutter-final-43726.firebaseapp.com',
    storageBucket: 'flutter-final-43726.firebasestorage.app',
    measurementId: 'G-MKZCK2J6SX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkA8Bh46P5cmGDPex_V488CxEBJTfZogA',
    appId: '1:966413108999:android:4608d006ecb49622a8e7a2',
    messagingSenderId: '966413108999',
    projectId: 'flutter-final-43726',
    storageBucket: 'flutter-final-43726.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeGh3Np2XUxpnmlexISaeu5h1bmIhN0fY',
    appId: '1:966413108999:ios:b5025245ca6cf159a8e7a2',
    messagingSenderId: '966413108999',
    projectId: 'flutter-final-43726',
    storageBucket: 'flutter-final-43726.firebasestorage.app',
    iosBundleId: 'com.example.flutterFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeGh3Np2XUxpnmlexISaeu5h1bmIhN0fY',
    appId: '1:966413108999:ios:b5025245ca6cf159a8e7a2',
    messagingSenderId: '966413108999',
    projectId: 'flutter-final-43726',
    storageBucket: 'flutter-final-43726.firebasestorage.app',
    iosBundleId: 'com.example.flutterFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrJ2NBr9ib1AdD0DKSXXogrPyBPGs1Rb0',
    appId: '1:966413108999:web:8c8dad7bc4f52eaea8e7a2',
    messagingSenderId: '966413108999',
    projectId: 'flutter-final-43726',
    authDomain: 'flutter-final-43726.firebaseapp.com',
    storageBucket: 'flutter-final-43726.firebasestorage.app',
    measurementId: 'G-YKHBHBQ62Q',
  );

}